name: authors_rest_api
dependencies: 
  angel_auth: ^1.1.0
  angel_configuration: ^1.1.0
  angel_file_service: ^1.0.0
  angel_framework: ^1.1.0
  angel_hot: ^1.1.0
  angel_model: ^1.0.0
  angel_security: ^1.1.0
  angel_serialize: ^1.0.0
  angel_validate: ^1.0.0
dev_dependencies: 
  angel_serialize_generator: ^1.0.0
  angel_test: ^1.1.0
  build_runner: ^0.5.0
  console: ^2.2.4
  test: ^0.12.0